[build]
  command = "npm run gulp watch"
  functions = "lambda"
  publish = "build"

[context.production]
  command = "npm run gulp watch"

[dev]
  command = "npm run gulp watch"
  port = 3000
  publish = "build"
